apiVersion: v1
kind: Service
metadata:
  name: homework-service
  namespace: homework
spec:
  type: ClusterIP
  selector:
    app: homework
  ports:
    - name: http
      port: 80
      targetPort: 8000
