apiVersion: apps/v1
kind: Deployment
metadata:
  name: angie-deployment
  namespace: homework
  labels:
    app: angie
spec:
  replicas: 3

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  selector:
    matchLabels:
      app: angie
      
  template:
    metadata:
      labels:
        app: angie
    spec:
      nodeSelector:
        homework: "true"

      containers:
      - name: nginx-fork
        image: docker.angie.software/angie:1.11.5-minimal
        # image: docker.angie.software/angie:1.11.6-minimal 
        ports:
        - containerPort: 8000
        volumeMounts:
        
        - name: shared-index-html
          mountPath: /homework

        - name: angie-config
          mountPath: /etc/angie/http.d/default.conf
          subPath: default.conf

        lifecycle:
          preStop:
            exec:
              command:
                - sh
                - -c
                - "rm -f /homework/index.html && sleep 5"

        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - 'test -f /homework/index.html && [ "$(wc -c < /homework/index.html)" -gt 0 ]'
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3


      initContainers:
      - name: wget-index-html
        image: busybox:1.38.0
        command:
        - wget
        - "-O"
        - "/init/index.html"
        - https://github.com/bralbral
        volumeMounts:
        - name: shared-index-html
          mountPath: /init

      volumes:
      - name: shared-index-html
        emptyDir: {}

      - name: angie-config
        configMap:
          name: angie-config


      