name: "Pull Request Labeler"

on:
  pull_request_target:

jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      contents: read        # To read the configuration file
      pull-requests: write  # To add labels
      issues: write         # Required for label operations
    steps:
      - name: Label PR
        uses: actions/labeler@v6
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true # Ensures labels are synced with your config