name: "Pull Request Labeler"

on:
  pull_request_target:

jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      contents: read        # Needed for the action to read your repo's code structure
      pull-requests: write  # Needed to add labels to the Pull Request
      issues: write         # CRITICAL: Needed because PR labels use the Issues API

    steps:
    - name: Label PR
      uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"