apiVersion: v1
kind: Pod
metadata:
  name: angie
  namespace: homework
spec:
  containers:
  - name: nginx-fork
    image: docker.angie.software/angie:1.11.6-minimal
    ports:
    - containerPort: 8000

